ethereum/devp2p

- rlpx.md
Every link in the `References` section has a `}` at the end of it that is encoded as `%7D` when the link is clicked. 
For example, the libp2p whitepaper link takes one to `https://github.com/ethereum/wiki/wiki/libp2p-Whitepaper%7D` which is not the correct url.
> Fix links for References in rlpx.md

- README.md
`trinity` has split off `py-evm` into its own repo.
> README: Link to current Trinity repo.

- discv5/discv5-wire.md
The enrs counter was still in the message
> discv5: fix topicnodes definition

- caps/eth.md
This spec was adapted from the content of the Ethereum wiki. The spec is
reformatted to include just the most recent version as well as a change
log listing past versions and their changes.
Sections explaining protocol semantics were expanded to cover block
propagation, full sync and fast sync as implemented in geth.
> caps/eth.md: add eth/63 protocol specification

- discv5/discv5-requirements.md
This change improves the markdown formatting of the document, cleaning
it up after the conversion from its original Microsoft Word form.
The confusion around the v4/v5 upgrade is removed by declaring both
networks separate and documenting the v4 -> v5 bootstrap procedure.
> discv5: reformat and extend requirements document

- README.md
- discv5/discv5-rationale.md
- discv5/discv5-theory.md
- discv5/discv5-wire.md
- discv5/discv5.md
This is my second pass over the spec after working on the implementation
for a while. Changes include:
- There is now a high-level intro document that ties the specs together.
- The 'topics' document is now 'theory' and contains a description of
the routing table, lookup etc. in addition to topic advertisement
content.
- Wire protocol is updated based on feedback from implementation.
- The new handshake replaces the WHOAREYOU and IAM messages
- conversation-nonce is removed in favor of a simple request-id
- NODES replaces NEIGHBORS and TOPICNODES
- message data lists are now up to date with reality
- All the 'maybes' and 'proposals' are removed from the spec text.
- The 'requirements' document is now 'rationale' but is otherwise
unchanged.
Closes #60
> discv5: add intro document, handshake, more theory

- discv5/discv5-wire.md
Adds further detail in the wire protocol, to describe the `random-packet`. 
This also re-orders `auth-response-rt` for consistency.
> discv5: fix definition of random-packet

- README.md
Link to libp2p wasn't up to date. since the change of domain from libp2p.org to libp2p.io
> README.md: update libp2p url from .org to .io

- caps/eth.md
The block number was added in eth/61 and removed in eth/62.
> caps/eth.md: remove block number from Status, fix link

- rlpx.md
There are some errors in the calculation of `MAC` and `header-mac-seed`.
> rlpx.md: fix some bugs

- discv5/discv5-wire.md
There's a error in the `PONG` response definition.
`packet-ip` and `packet-port` should be `recipient-ip` and `recipient-port` as per the definition of `message-data`.
> discv5: fix definition of PONG response

- discv5/discv5-wire.md
While trying to understand the spec, I noticed that there's notation that is used but ends up being defined later in the spec. It's much easier to define notation that is going to be used throughout the spec beforehand instead of using it and then defining the notation.
> Moved notation section to earlier in the spec

- discv5/discv5-wire.md
I added a message type property to all protocol messages definitions as these should be sent across the wire as part of the packet.
> discv5: add message-type definitions to all protocol messages

- discv5/discv5-rationale.md
- discv5/discv5-theory.md
- discv5/discv5-wire.md
- discv5/discv5.md
The rationale is now up-to-date with the wire protocol. The 'scenario'
descriptions were removed because they were hard to maintain. All of
them were outdated because the handshake didn't exist when they were
written.
These changes were made to get the wire protocol spec up-to-date with
the Go implementation:
- WHOAREYOU no longer has a tag prefix because it could be used
to recover the node's ID.
- auth-response-pt contains a protocol version number.
- node-record in auth-response-pt is `[]` if absent. The spec said
it is sent if local seq is higher but didn't define the RLP encoding.
- auth-header contains a reference to id-nonce prevent handshake replay.
- REGTOPIC requires sending the current node record.
Fixes #80 
Fixes #89 
Fixes #79
> discv5: rationale update, minor spec changes

- rlpx.md
In all current implementations, the frame size refers to the compressed
length of the message. The uncompressed length is encoded as a varint at
the beginning of the compressed msg-data payload.
> rlpx.md: correct description of snappy frame-size

- discv5/discv5.md
The other docs were updated to note `5.1` and this document still said it was a draft from 2019 Oct.
> discv5: update discv5.md with the v5.1 version number

- caps/snap.md
The old formulation is misleading, lending to the false assumption that the hash is the hash of the RLP and not the trie path.
> caps/snap.md: clarify hash in range responses

- README.md
- caps/pip.md
- caps/wit.md
This simple budding protocol has been successfully tested among a couple cooperating clients. It is tremendously useful for Beam Sync. Let me know if there's anything I can do to help get it approved & merged!
Large chunks were shamelessly stolen from the `snap` protocol PR, so thanks to Peter for that.
> caps/wit.md: Ethereum Witness Protocol v0

- rlpx.md
Limiting the number of characters in capability name so that it can be saved as u64 number.
> rlpx.md: add capability name character limit

- caps/eth.md
This adds a lot of new text to cover the encoding and validity of
consensus objects. We previously referred to the 'main Ethereum
specification' for that, but no such specification exists in practice.
There is also a new entry in the changelog to cover the addition of
EIP-2718 typed transactions in the wire protocol. 
Fixes #160
> caps/eth.md: specify encoding of all consensus objects

- rlpx.md
The Message ID section of rlpx.md appears to be incorrect:
> Message IDs are assumed to be compact from ID **0x11 onwards (0x00-0x10 is
reserved for the "p2p" capability)** and given to each shared (equal-version,
equal-name) capability in alphabetic order.
It says the message IDs of capabilities start at 0x11, but in reality (e.g. checked Geth, OpenEthereum, Nimbus) the "eth" capability starts at 0x10, so the reserved range for "p2p" is 0x00-0x0f.
> rlpx.md: capability message IDs start at 0x10, not 0x11

- caps/snap.md
according to discussion on https://github.com/ethereum/go-ethereum/issues/23536, this adds 'limit' on GetAccountRange and GetStorageRange. 
cc @matkt @karalabe
> caps/snap.md: add limit parameter in range requests

- discv5/discv5-theory.md
Specify that the XOR distance, when taken as a number, is the big-endian number.
This seems to be true for all implementations, but this is not specified.
- [ChainSafe](https://github.com/ChainSafe/discv5/blob/master/src/kademlia/util.ts#L11)
- [Status](https://github.com/status-im/nim-eth/blob/master/eth/p2p/kademlia.nim#L55)
- [Sigma Prime](https://github.com/sigp/discv5/blob/master/src/kbucket/key.rs#L81)
- [U256](https://github.com/paritytech/parity-common/blob/master/uint/src/uint.rs#L1368)
> discv5: specify endianness of XOR distance

- rlpx.md
One line change to update the link to the RLP wiki
> rlpx.md: update link to RLP wiki page

- caps/eth.md
This PR defines protocol version eth/67, applying the changes proposed by [EIP-4938](https://eips.ethereum.org/EIPS/eip-4938).
> caps/eth.md: eth/67 - removal of GetNodeData

- README.md
Since the version is now 67 (#208), the README should be updated to reflect that :)
> README.md: update eth protocol version

- README.md
- discv4.md
Restricting `i` to `[0, 256)` suggests that max XOR distance representable by a k-bucket is `[510, 511]` (when `i=255`). Given that a node public key is 512 bits (64 bytes), this means that if the first bit doesn't match (XOR distance of 512, half of all nodes), it cannot be stored in a k-bucket. Another minor issue is that the `i=0` bucket represents distances `[0, 1]`, but a node is only at distance 0 from itself?
I believe the author implied i's range to be `(0, 256]`, with each k-bucket representing distances in `[2i-1, 2i]`. This way, the `i=256` bucket represents distances `[511, 512]`, and the `i=1` bucket represents `[1, 2]`.
> discv4: fix definition of node k-bucket distances

- discv5/discv5-theory.md
- discv5/discv5-wire.md
@fjl and I made this fantastically optimised NAT hole punch protocol! @fjl I can't add you as a reviewer after creating the PR. [nat_msg](https://user-images.githubusercontent.com/58548332/228539653-3ea76aca-fd11-48b3-9236-cf996e0d7892.png)
Implemented and tested https://github.com/emhane/nat_hole_punch/tree/standardise-nat-hole-punch
> discv5: NAT hole punching wire protocol

- caps/eth.md
This changes the definition of block data validity rules to include withdrawals.
> caps/eth.md: add changes for withdrawals (EIP-4895)

- discv4.md
I am confused。According to the document， the entries are sorted by time last seen — least-recently seen node at the head, most-recently seen at the tail. why is the new node added to the front of the bucket
> discv4.md: update text about node ordering in bucket

- caps/eth.md
Due to an implementation flaw in go-ethereum and other clients, we have decided to change the encoding of the `txtypes` list into a byte array.
> caps/eth.md: change encoding of eth/68 tx announcement

- rlpx.md
Specify the `listenPort` parameter from the `hello` packet as legacy, mention that it's not used anymore.
> rlpx.md: document hello.listenPort as legacy

- caps/eth.md
Clarifies that size metadata in `NewPooledTransactionHashes` refers to the rlp encoded length of a transaction ~~+ header~~ without header. Thanks @Rjected.
> caps/eth.md: clarify size in NewPooledTransactionHashes

- discv5/discv5-theory.md
The current version of the spec gives the impression that `NEIGHBORS` is the response to the `FINDNODE` request, while `NODES` is the actual response.
(There is no `NEIGHBORS` response defined in `discv5-wire.md`)
> discv5: fix typo NEIGHBORS -> NODES

- discv5/discv5-wire-test-vectors.md
- plaintext (4 bytes): `0x01c20101`
- ciphertext (4 bytes): `0xa5d12a2d`
- MAC (16 bytes): `0x94b8ccb3ba55558229867dc13bfa3648`
==> The 16 bytes MAC is appended to the ciphertext, not prepended.
> discv5: fix typo
